version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=mysecretpassword1234"
    expose:
      - "3000"
    links:
      - db
    volumes:
      - ".:/app"
      - "bundle:/app/vendor/bundle"
    stdin_open: true

  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword1234"

volumes:
  postgres:
  bundle:
